theme: minima
title: Minorities In Action
author: Muhammad Ibin Abdur-Rahim
description: We draw for food & money. We love our families & friends, Creating Art, playing video games, and trying to earn a living doing what we want to do. Not what we have to do.
